<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- 多目标框架：Standard2.0 + .NET5 + .NET8(AOT) -->
		<TargetFrameworks>netstandard2.0;net5.0;net8.0</TargetFrameworks>
		<Version>2026.5.4</Version>
		<Authors>Delly.Net</Authors>
		<Description>MySQL provider for Delly.DBunny</Description>
		<PackageIcon>Bunny_128.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>db database mysql sql data provider mariadb dbunny netstandard dotnet dotnet5 dotnet8 aot</PackageTags>
		<RepositoryUrl>https://github.com/delly-net/DBunny</RepositoryUrl>
	</PropertyGroup>

	<!-- 仅给支持的框架开启 Nullable -->
	<PropertyGroup Condition="'$(TargetFramework)'!='netstandard2.0'">
		<Nullable>enable</Nullable>
			<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
	</PropertyGroup>

	<!-- 仅对 net8.0 开启 -->
	<PropertyGroup Condition="'$(TargetFramework)'=='net8.0'">
		<IsAotCompatible>true</IsAotCompatible>
		<PublishAotCompilationEnabled>true</PublishAotCompilationEnabled>
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Delly.DBunny.Core\Delly.DBunny.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\Document\Logo\Bunny_128.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>